service: serverless-framework-app

package:
  individually: true
  patterns:
    - "!*/**"
    - "!eslint.config.mjs"
    - "src/constants.js"
    - "src/lib/dynamodb.js"
    - "src/utils/unwrapTypes.js"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: !GetAtt DynamoDB.Arn
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource: !Sub ${S3Bucket.Arn}/*
  apiGateway:
    apiKeys:
      - serverless-framework-app
  environment:
    SECRET_KEY: ${ssm:/SECRET_KEY}

plugins:
  - serverless-lift
  - serverless-plugin-typescript
  - serverless-apigateway-service-proxy

layers:
  nodejs:
    name: "nodejs-sls-app-layer"
    compatibleRuntimes:
      - ${self:provider.runtime}
    package:
      artifact: layer-artifacts/nodejs.zip

functions:
  get-user:
    handler: src/functions/get-user/index.handler
    description: Returns the information of a single user
    package:
      patterns:
        - "src/functions/get-user/*"
    events:
      - http:
          private: true
          path: users/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true

  get-users:
    handler: src/functions/get-users/index.handler
    description: Returns a list of users
    package:
      patterns:
        - "src/functions/get-users/*"
    events:
      - http:
          private: true
          path: users
          method: GET
          request:
            parameters:
              querystrings:
                lastKey: false

  create-user:
    handler: src/functions/create-user/index.handler
    description: Allows to register a new user into the application
    package:
      patterns:
        - "src/functions/create-user/*"
    events:
      - http:
          path: users
          method: POST
          authorizer:
            name: custom-authorizer
            resultTtlInSeconds: 15
          request:
            schemas:
              application/json: ${file(src/schemas/user.json)}
  
  update-user:
    handler: src/functions/update-user/index.handler
    description: Allows to update a user record
    package:
      patterns:
        - "src/functions/update-user/*"
    events:
      - http:
          path: users/{id}
          method: PUT
          authorizer:
            name: custom-authorizer
            resultTtlInSeconds: 15
          request:
            parameters:
              paths:
                id: true
            schemas:
              application/json:
                schema: ${file(src/schemas/user.json)}
                name: PostCreateModel
                description: 'Validation model for creating users'

  delete-user:
    handler: src/functions/delete-user/index.handler
    description: Allows to delete a user record
    package:
      patterns:
        - "src/functions/delete-user/*"
    events:
      - http:
          path: users/{id}
          method: DELETE
          authorizer:
            name: custom-authorizer
            resultTtlInSeconds: 15
          request:
            parameters:
              paths:
                id: true
  
  create-signed-upload-url:
    handler: src/functions/create-signed-upload-url/index.handler
    description: Returns a signed S3 URL to upload an image
    package:
      patterns:
        - "src/functions/create-signed-upload-url/*"
        - "src/lib/s3.js"
        - "!src/lib/dynamodb.js"
        - "!src/utils/unwrapTypes.js"
    environment:
      AWS_S3_BUCKET_NAME: ${self:custom.aws-bucket-name}
    events:
      - http:
          path: signed-url
          method: POST
          authorizer:
            name: custom-authorizer
            resultTtlInSeconds: 15
          request:
            schemas:
              application/json: ${file(src/schemas/signed-url.json)}

  thumbnail-generator:
    handler: src/functions/thumbnail-generator/index.handler
    layers:
      - { Ref: NodejsLambdaLayer }
    package:
      patterns:
        - "!src/lib/dynamodb.js"
        - "!src/utils/unwrapTypes.js"
        - "src/functions/thumbnail-generator/*"
        - "src/lib/s3.js"
        - "nodejs.zip"
    events:
      - s3:
          bucket: ${self:custom.aws-bucket-name}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: upload/

  custom-authorizer:
    handler: src/functions/authorizer/index.handler
    package:
      patterns:
        - "!src/lib/dynamodb.js"
        - "src/functions/authorizer/*"

custom:
  aws-bucket-name: serverless-framework-app-janr-test-1-dev
  apiGatewayServiceProxies:
    - sqs:
        path: /like-user
        method: POST
        queueName: like-user-queue
        cors: true
        response:
          template:
            success: |-
              { "message": "accepted" }
            clientError: |-
              { "message":  "there is an error in your request" }
            serverError: |-
              { "message": "there was an error handling your request" }

constructs:
  sqs-queue:
    type: queue
    batchSize: 1
    worker:
      handler: src/functions/like-user/index.handler
      reservedConcurrency: 1
      package:
        patterns:
          - "!src/lib/*"
          - "src/functions/like-user/*"
    extensions:
      queue:
        Properties:
          QueueName: like-user-queue

resources:
  Resources:
    DynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        PublicAccessBlockConfiguration:
          RestrictPublicBuckets: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          BlockPublicAcls: false
        BucketName: ${self:custom.aws-bucket-name}
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerPreferred
    S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: statement1
              Resource: !Sub ${S3Bucket.Arn}/*
              Effect: "Allow"
              Principal: "*"
              Action:
                - "s3:GetObject"
