service: serverless-framework-aws

package:
  individually: true
  patterns:
    - "**/**"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: !GetAtt usersDb.Arn

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb

custom:
  serverless-dynamodb:
    start:
      port: 8000
      docker: false
      inMemory: true
      migrate: true
      seed: true

    seed:
      users:
        sources:
          - table: usersTable
            sources: ['./local-seeders/users.json']

resources:
  Resources:
    usersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  get-user:
    handler: src/functions/get-user/index.handler
    description: Returns the information of a single user
    package:
      patterns:
        - "src/functions/get-user"
        - "src/lib"
        - "src/constants.ts"
    events:
      - http:
          path: users/{id}
          method: GET

  get-users:
    handler: src/functions/get-users/index.handler
    description: Returns a list of users
    package:
      patterns:
        - "src/functions/get-user"
        - "src/lib"
        - "src/constants.ts"
        - "src/utils/unwrapTypes.ts"
    events:
      - http:
          path: users
          method: GET

  create-user:
    handler: src/functions/create-user/index.handler
    description: Allows to register a new user into the application
    package:
      patterns:
        - "src/functions/get-user"
        - "src/lib"
        - "src/constants.ts"
        - "src/utils/unwrapTypes.ts"
    events:
      - http:
          path: users
          method: POST
  
  update-user:
    handler: src/functions/update-user/index.handler
    description: Allows to update a user record
    package:
      patterns:
        - "src/functions/get-user"
        - "src/lib"
        - "src/constants.ts"
        - "src/utils"
    events:
      - http:
          path: users/{id}
          method: PUT

  delete-user:
    handler: src/functions/delete-user/index.handler
    description: Allows to delete a user record
    package:
      patterns:
        - "src/functions/get-user"
        - "src/lib"
        - "src/constants.ts"
        - "src/utils/unwrapTypes.ts"
    events:
      - http:
          path: users/{id}
          method: DELETE
