name: Unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Automated Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: NPM - Load cached env
        id: cached-npm-dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}
      
      - name: NPM - Install dependencies
        if: steps.cached-npm.dependencies.output.cache-hit != 'true'
        run: 'npm install'

      - name: Run tests
        run: npm test
