name: Deploy DEV

on:
  pull_request:
    branches: [main]

jobs:
  testing-changes:
    runs-on: ubuntu-latest
    name: Build/Test
    steps:
      - uses: actions/checkout@v4

      - name: NPM - Install dependencies
        if: steps.cached-npm-dependencies.output.cache-hit != 'true'
        run: 'npm install'

      - name: Run Tests
        run: |
          npm run test

  deploy-env:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    needs: testing-changes
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: NPM - Load cached venv
        id: cached-npm-dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: NPM - Install dependencies
        if: steps.cached-npm-dependencies.output.cache-hit != 'true'
        run: 'npm install'

      - name: Deploy using sls
        run: 'npx sls deploy'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Your SLS App was deployed!
            Awesome
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
